### ISSUE TITLE
GraphQL Error when trying to create new operation

### ISSUE THREAD

**Issue by rpgmaster280** [MythicMeta/Mythic_Scripting#1]
When attempting to create a new operation using the GraphQL API v0.0.30 and version 2.3.8 of Mythic, the create_operation function fails.
```
await mythic.create_operation(
    mythic=mythic_instance,
    operation_name="Operation Test"
)
```

The error reported is as follows:
```
graphql.error.graphql_error.GraphQLError: Unknown type 'createOperation'. Did you mean 'operatoroperation', 'createOperationOutput', or 'operation'?

GraphQL request:8:43
7 |     
8 |     fragment create_operation_fragment on createOperation {
  |                                           ^
9 |         status

```

**Comment by rpgmaster280** [comment]
Inspecting the request in the mythic GUI, it appears that the function was renamed to newOperationMutation.

**Comment by its-a-feature** [comment]
Ah, I see the issue. The fragment should be on createOperationOutput. I'll do an update to fix it now

**Comment by rpgmaster280** [comment]
Awesome. Wasn't expecting a fast reply. I'll update the related python file in the meanwhile =)

**Comment by its-a-feature** [comment]
Ok, you should be able to pull down version 0.0.31 with the fix! Sorry about that
