### ISSUE TITLE
GraphQL query failure

### ISSUE THREAD

**Issue by spankywetfish** [MythicMeta/Mythic_Scripting#5]
There appears (to my limited knowledge/capabilities) to be a coding error in in `mythic/mythic.py` at line 193.

```
    query = f"""
    query CurrentCallbacks{{
        callback(where: {{active: {{_eq: true}}, order_by: {{id: asc}}){{
            {custom_return_attributes if custom_return_attributes is not None else '...callback_fragment'}
        }}
    }}
    {graphql_queries.callback_fragment if custom_return_attributes is None else ''}
    """
```

This results in the following error for me.

```
GraphQL request:3:66
2 |     query CurrentCallbacks{
3 |         callback(where: {active: {_eq: true}, order_by: {id: asc}){
  |                                                                  ^
4 |
```
The fix would seem to be to modify line 193 to add the missing `}}` as per...

`callback(where: {{active: {{_eq: true}}, order_by: {{id: asc}}}}){{`

**Comment by its-a-feature** [comment]
You're exactly right! Thanks for catching that. I've updated it in version 0.0.35 now
