### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by linted** [MythicMeta/Mythic_Scripting#9]
Hello!
I have been trying to use this scripting API to automate a few processes, but for various reasons I am stuck with the previous release of mythic. Because this repo doesn't have any branches or tags, it makes it very difficult to inspect the api using the github web site. 

Is it possible to start tagging release commits so they can more easily be reviewed or checked out?

**Comment by its-a-feature** [comment]
Ah good point! I have tagged versions for a lot of Mythic components, but this one must have slipped by. What version of Mythic are you using?

**Comment by linted** [comment]
I'm using mythic `v2.3.13` which seems to correspond to version 0.0.38 of this scripting library

**Comment by its-a-feature** [comment]
I created a new tagged version of the code for `v0.0.38` which is the point in time for mythic 2.3.13

**Comment by its-a-feature** [comment]
did that work for you? If so, i'll be sure to add tagged releases for each mythic version

**Comment by linted** [comment]
Yes, that helps immensely!
